# Generated by Django 4.1 on 2024-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_author_genres_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="genres",
            field=models.ManyToManyField(to="books.genre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="books.genre"),
        ),
    ]
