# Generated by Django 4.1 on 2024-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_author_genres_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="genres",
            field=models.ManyToManyField(blank=True, to="books.genre"),
        ),
    ]
