# Generated by Django 4.1 on 2024-02-18 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_author_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="genres",
        ),
    ]
